source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DLZip_Example', :exclusive => true do
  pod "DLZip", :path => "../"
end

target 'DLZip_Tests', :exclusive => true do
  pod "DLZip", :path => "../"

  
end
